### ISSUE TITLE
Facing Issue on cpanel hosting

### ISSUE THREAD

**Issue by ghost** [GeniusTS/hijri-dates#10]
I have installed hijre-dates with composer in codeigniter.

I am facing following issue while i upload my application on cpanel hosting

Fatal error: Default value for parameters with a class type hint can only be NULL in /home/xxxxx/public_html/sms/vendor/geniusts/hijri-dates/src/Hijri.php on line 64

**Comment by aboudeh87** [comment]
Sorry for late response, What is the PHP version on the server?
