### ISSUE TITLE
I don't think it's working correctly!

### ISSUE THREAD

**Issue by tamkeen-tms** [GeniusTS/hijri-dates#14]
```php
$now = \GeniusTS\HijriDate\Date::now();
$now->format('l d F o', Date::INDIAN_NUMBERS);
```
It returns `Tuesday ٢٧ Rajab ١٤٤٠`, which is actually not correct; it's __26__ Rajab 1440.
Am I doing something wrong ?

Thanks in advance.

**Comment by aboudeh87** [comment]
No you didn't as you know the Hijri date depends on moon vezion, so there is some wrong dates appear on calculations, when that happen you should use adjustment to fix the issue
