### ISSUE TITLE
Hijri Date is not correct

### ISSUE THREAD

**Issue by AmirAmin** [GeniusTS/hijri-dates#15]
Hello,

The Hijri Date is not correct, For ex. It is showing that Ramadan has started yesterday (May 5th). 

Although it is either today (May 6th) or tomorrow (May 7th).

Best Regards,

**Comment by AmirAmin** [comment]
I have fixed it using:

\GeniusTS\HijriDate\Hijri::setDefaultAdjustment(-1);

But I am not sure if it is the correct solution or not.

**Comment by AmirAmin** [comment]
> I have fixed it using:
> 
> \GeniusTS\HijriDate\Hijri::setDefaultAdjustment(-1);
> 
> But I am not sure if it is the correct solution or not.

It will fix the upcoming, and set the old dates wrong.

**Comment by aboudeh87** [comment]
> > I have fixed it using:
> > \GeniusTS\HijriDate\Hijri::setDefaultAdjustment(-1);
> > But I am not sure if it is the correct solution or not.
> 
> It will fix the upcoming, and set the old dates wrong.

Yes because this function set the default adjustment for all dates,
use the second parameter of `convertToHijria method Eg.: `Hijri :: convertToHijri ($date, -1)`
