### ISSUE TITLE
Default value for parameters with a class type hint can only be NULL

### ISSUE THREAD

**Issue by ahmedyaghi** [GeniusTS/hijri-dates#2]
it's happen when uploaded the project to the server and it's work localhost

**Comment by ahmedyaghi** [comment]
The problem appears in this code

protected static function toHijri(Carbon $date, int $adjustment = 0)
    {
        $adjusted = (new Carbon($date))->addDays($adjustment);
 
        $jd = Converter::gregorianToJulian($adjusted->year, $adjusted->month, $adjusted->day);
        $hijri = Converter::julianToHijri($jd);
 
        return new Date($hijri->day, $hijri->month, $hijri->year, $jd, clone $date, $adjustment);
    }

**Comment by aboudeh87** [comment]
Sorry the issue is not clear

**Comment by ahmedyaghi** [comment]
have a look here 
http://ahmedyaghi.com/basic/

**Comment by aboudeh87** [comment]
Still not clear the link open a website

**Comment by ahmedyaghi** [comment]
I just updated the PHP version to 7.1 and it's work :+1:
