### ISSUE TITLE
cannot install with ssh

### ISSUE THREAD

**Issue by falmahdi** [GeniusTS/hijri-dates#3]
in SSH I tried to run:
composer require geniusts/hijri-dates

but I recieve the error:
[InvalidArgumentException]  Could not find package geniusts/hijri-dates at any version matching your PHP version 5.6.31.0  

I'm on BLUEHOST.COM shared server. Using php 7.0.12 However when I run "php -v" on SSH I get php 5.6.31.0 !!! Any Idea why ?

Thanks for your efforts

**Comment by aboudeh87** [comment]
most of shared server run PHP version 5 in the console try to find the path of PHP7 in your server, I don't know it in BLUEHOST, but in HOSTGATOR is `/opt/php71/bin/php`

**Comment by falmahdi** [comment]
Thank you so much Aboudeh. It works well now. For future Bluehost clients here is what I did:
in Bluehost control panel: 
-Find PHP Configuration icon
-Select php 7
-Save

Then in SSH:
export PATH=/opt/php70/bin:$PATH
mkdir ~/common
cd ~/common
composer require nesbot/carbon
composer require geniusts/hijri-dates

in my php script I added:
require_once '../../common/vendor/autoload.php';
(or whatever path you wish to store the common directory)

I tested your work and it's awsome

**Comment by falmahdi** [comment]
With all respect. your name is Abdul-Kader Zein-Eddin
