### ISSUE TITLE
convertToGregorian problem

### ISSUE THREAD

**Issue by sehsah** [GeniusTS/hijri-dates#4]
hi , 
how can convertToGregorian by formate 1439-05-05
like convertToHijri

**Comment by aboudeh87** [comment]
Use `explode` function before call the `convertToGregorian` function

**Comment by sehsah** [comment]
when i use this format
        $newdate = \GeniusTS\HijriDate\Hijri::convertToGregorian(2 - 11 - 1439);

Type error: Argument 2 passed to GeniusTS\HijriDate\Hijri::convertToGregorian() must be of the type integer, none given, called in

**Comment by aboudeh87** [comment]
it should be like the following

`
$newdate = \GeniusTS\HijriDate\Hijri::convertToGregorian(2, 11, 1439);
`

**Comment by sehsah** [comment]
ok thank u

**Comment by aboudeh87** [comment]
you are welcome

**Comment by sehsah** [comment]
$date1 = 11; $date1 = 2; $date1 = 1439;
        $newdate = \GeniusTS\HijriDate\Hijri::convertToGregorian($date1 , $date2 , $date3);

also Error 👎

**Comment by sehsah** [comment]
ok it's worked ;)

**Comment by aboudeh87** [comment]
you don't have `$date2` and `$date3` variables in your code :)
