### ISSUE TITLE
Default value for parameters with a class type hint can only be NULL

### ISSUE THREAD

**Issue by sehsah** [GeniusTS/hijri-dates#5]
the code worked well on localhost
when upload it on server 
Error showed me 

![image](https://user-images.githubusercontent.com/8730764/32325178-f3690296-bfde-11e7-834f-bb156abd857c.png)

**Comment by aboudeh87** [comment]
What is the PHP version on the server?

**Comment by sehsah** [comment]
5.6

**Comment by sehsah** [comment]
thank u it's worked when uprgade php version  to  7.0
