### ISSUE TITLE
how to get date in arabic text not number

### ISSUE THREAD

**Issue by deva7mad** [GeniusTS/hijri-dates#6]
use GeniusTS\HijriDate\Translations\Arabic;
\GeniusTS\HijriDate\Date::setTranslation(new Arabic);
what should i do to get date in string 
$ar_date = \GeniusTS\HijriDate\Date::now();

**Comment by aboudeh87** [comment]
You can use `format` method

**Comment by nawinsoft** [comment]
Please guide me how to use this library in my PHP file.

**Comment by aboudeh87** [comment]
You can use [composer](https://getcomposer.org) to download it, If you are not using it
you should create an PSR-4 autoloader for the package
